CREATE TABLE tb_client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome_cliente VARCHAR(100) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL,
    data_cadastro DATE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE tb_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    numero_pedido VARCHAR(20) NOT NULL UNIQUE,
    descricao VARCHAR(500) NOT NULL,
    valor_total DECIMAL(10, 2) NOT NULL,
    data_pedido DATE NOT NULL,
    cliente_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (cliente_id) REFERENCES tb_client(id)
);
